---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: "3-jdk-8-alpine"

inputs:
- name: source-code

outputs:
- name: package-output

run:
  path: source-code/loan-approval-service/ci/tasks/build-loan-checker.sh
