---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu
    tag: "latest"

params:
  URL:

inputs:
- name: source-code

run:
  path: source-code/loan-approval-service/ci/tasks/smoke-test-loan-checker.sh