management:
  endpoints:
    web:
      exposure:
        include: "*"

max-loan-amount: 10000

approvals:
  naughtylist:
    - trunp

server:
  port: 80

logging:
  level:
    org:
      springframework:
        cloud:
          netflix:
            eureka: OFF
          config:
            client: OFF
    com:
      netflix:
        discovery: OFF
